import Footer from "@/components/custom/footer/Footer";
import "./globals.scss";
import Nav from "@/components/custom/nav/Nav";
import { lato } from "./font";

export const metadata = {
  title: "David cleaning service",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Nav />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
